services:
  bridgebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridgebot
    restart: always
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MINECRAFT_EMAIL=${MINECRAFT_EMAIL}
      - BRIDGE_CHANNEL_ID=${BRIDGE_CHANNEL_ID}
      - LOG_IN_OFF_CHANNEL_ID=${LOG_IN_OFF_CHANNEL_ID}
      - KICK_CHANNEL_ID=${KICK_CHANNEL_ID}
      - PROMOTE_DEMOTE_CHANNEL_ID=${PROMOTE_DEMOTE_CHANNEL_ID}
      - LEAVE_JOIN_CHANNEL_ID=${LEAVE_JOIN_CHANNEL_ID}
